version: '3.3'

services:

  zammad-backup:
    build:
      context: .
      dockerfile: containers/zammad-postgresql/Dockerfile
    depends_on:
      - zammad-railsserver
    links:
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
      - backup-zammad:/var/tmp/zammad
    entrypoint: /usr/local/bin/backup.sh  
    command: ["zammad-backup"]

  zammad-elasticsearch:
    build:
      context: .
      dockerfile: containers/zammad-elasticsearch/Dockerfile
    restart: always

  zammad-nginx:
    build:
      context: .
      dockerfile: containers/zammad-nginx/Dockerfile
    depends_on:
      - zammad-railsserver
    links:
      - zammad-railsserver
      - zammad-websocket
    ports:
      - "80:80"
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-postgresql:
    build:
      context: .
      dockerfile: containers/zammad-postgresql/Dockerfile
    restart: always

  zammad-railsserver:
    build:
      context: .
      dockerfile: containers/zammad/Dockerfile
    depends_on:
      - zammad-postgresql
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
    command: ["zammad-railsserver"]

  zammad-scheduler:
    build:
      context: .
      dockerfile: containers/zammad/Dockerfile
    depends_on:
      - zammad-railsserver
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
    command: ["zammad-scheduler"]

  zammad-websocket:
    build:
      context: .
      dockerfile: containers/zammad/Dockerfile
    depends_on:
      - zammad-railsserver
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
    command: ["zammad-websocket"]

volumes:
  backup-zammad:
    driver: local
  data-zammad:
    driver: local
